name: "Test"
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Install pnpm
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0

      - name: Setup Node.js
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: ".node-version"
          cache: "pnpm"

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Lint
        run: |
          pnpm run lint

      - name: Check pinact
        uses: suzuki-shunsuke/pinact-action@28aeb220eb3252ad0d4422dd5d9368e925acbd8d # v1.3.0
        with:
          skip_push: "true"
          min_age: "7"

      - name: Test Dry Run
        run: |
          pnpm run run:collect-artifacts --fetchUrlOnly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
